steps:
  # Step 1: Run tests
  - name: maven:3.8.4-openjdk-17
    entrypoint: mvn
    args: ['test']

  # Step 2: Package the application
  - name: maven:3.8.4-openjdk-17
    entrypoint: mvn
    args: ['package', '-Dmaven.test.skip=true']

  # Step 3: Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/shortenerurl-437517/urlshortnerservice', '.']

  # Step 4: Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/shortenerurl-437517/urlshortnerservice']

  # Step 5: Deploy the container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'urlshortnerservice'
      - '--image'
      - 'gcr.io/shortenerurl-437517/urlshortnerservice'
      - '--region'
      - 'europe-west1'
      - '--platform'
      - 'managed'
      - '--set-env-vars'
      - 'SPRING_PROFILES_ACTIVE=neon'
      - '--set-secrets'
      - 'DB_PASSWORD=DB_PASSWORD:latest'
      - '--allow-unauthenticated'
      - '--timeout'
      - '5m'
      - '--memory'
      - '512Mi'

options:
  logging: CLOUD_LOGGING_ONLY

images:
  - "gcr.io/shortenerurl-437517/urlshortnerservice"
