server:
  port: ${PORT:8080}
  error:
    whitelabel:
      enabled: false
    path: /404

spring:
  datasource:
    url: jdbc:postgresql://ep-flat-block-a2i8n4ng.eu-central-1.aws.neon.tech/ShortnerURL?sslmode=require
    username: ShortnerURL_owner
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
    com.zaxxer.hikari: DEBUG