server:
  port: 8080
  error:
    whitelabel:
      enabled: false
    path: /404

spring:
  datasource:
    url: jdbc:postgresql://localhost:8081/ShortnerURL
    username: postgres
    password: pass
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect